export enum Classification {
  Action = 'Action',
  Alien = 'Alien',
  Ally = 'Ally',
  Broom = 'Broom',
  Captain = 'Captain',
  Deity = 'Deity',
  Detective = 'Detective',
  Dragon = 'Dragon',
  Dreamborn = 'Dreamborn',
  Fairy = 'Fairy',
  Floodborn = 'Floodborn',
  Hero = 'Hero',
  Hyena = 'Hyena',
  Inventor = 'Inventor',
  Item = 'Item',
  King = 'King',
  Knight = 'Knight',
  Madrigal = 'Madrigal',
  Mentor = 'Mentor',
  Musketeer = 'Musketeer',
  Pirate = 'Pirate',
  Prince = 'Prince',
  Princess = 'Princess',
  Queen = 'Queen',
  Racer = 'Racer',
  SevenDwarfs = 'Seven Dwarfs',
  Song = 'Song',
  Sorcerer = 'Sorcerer',
  Storyborn = 'Storyborn',
  Tigger = 'Tigger',
  Villain = 'Villain',
  Puppy = 'Puppy',
  Titan = 'Titan',
}

export const Classifications = Object.values(Classification);
